# Enable C++ support
language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt-5.12.0-bionic
    packages:
    - qt512[QTPACKAGE]
    - qt512script
    - qt512xmlpatterns
    - mesa-common-dev
    - libglu1-mesa-dev
  homebrew:
    packages:
    - llvm
    - libomp
    - qt

matrix:
  include:
    - os: osx
      osx_image: xcode11
    
    - os: linux
      dist: bionic
      sudo: required
      
git: 
  depth: 1

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
       export CXX = /usr/local/opt/llvm/bin/clang++
       npm install -g appdmg
       echo "appdmg version: " 
       npm list --depth=0
       export COLUMNS=80
          
       #Set up Qt from brew
       export QTDIR=/usr/local/opt/qt
       export PATH=$QTDIR/bin:$PATH
       export LD_LIBRARY_PATH=$QTDIR/lib:$LD_LIBRARY_PATH
       export PKG_CONFIG_PATH=$QTDIR/lib:$PKG_CONFIG_PATH
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      export QMAKESPEC="linux-clang"      
    fi
  - cd ..
  - git clone --depth=1 --branch=devel https://github.com/cnr-isti-vclab/vcglib.git
  - cd meshlab

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="/usr/local/opt/llvm/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then which clang             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then LDFLAGS=-L$QTDIR/lib            ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then CPPFLAGS=-I$QTDIR/include        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"   ]]; then source /opt/qt512/bin/qt512-env.sh        ;fi
  - cd src
  - cd external
  - qmake --version
  - qmake 
  - make -j4
  - cd ..
  - qmake meshlab_full.pro
  - make -j4

#after_success:
#  - |
#    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
#    then
#      pwd
#      ls distrib
#      cd install/macx
#      ./macinstall_v2018.sh
#      pwd
#      echo "------ Completed!!! We should have a dmg here "
#      cd ../../..
#      ls -la src/distrib/MeshLab201804.dmg      
#    fi
#before_deploy:
#  - ls -la src/distrib/MeshLab201804.dmg
#  - git config --local user.name "cignoni"
#  - git config --local user.email "cignoni@isti.cnr.it"
#  #- git tag "MeshLab-$(date +'%Y%m%d')-$(echo 'beta')"
#  - git tag "$(git log --format=%h -1)"
#  #- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
#deploy:
#  overwrite: true
#  provider: releases
#  api_key:
#    secure: DwQcZjW9DJQvfSh0hIc1xHu3mrX6TJ5IqEBz8H6W4Y+/hln4+qGHBBqYBB2KfdhA1Tlb0cy6vthZIVXWL0LWdFVX9Al8hZeQ1EXIJO3WlqTqZUQgy01lgT5FxXBDeaACH9+InyGM2nXw3i0WJW+bUdWJ2dQQaDyEc+JMmvg5Pi5vzK4DusbpBxZkL0T2egfJuxlNi+C5a8kPu31L6uew5pf5EhBEcjLjayB+QulfX9XN/cmGqFIy8+nlRXjay7dankCsOaznEbZh9PRzeLX+YO2A5qVHtcJpBxMkm50BhpuWQtSFa8JA08spVhVABCB7sY35qL2BzVJH0KeoqNKZRBOAkLSvQefyg7nAR093YUiB+1LgyefBZWU17THMjp2XMwyYsA57eF58EPP3uZal/w2voQ1FgZh7uIN+2b/lXl2qBm0dy4E9XGNR+hSsTJOQd5VNPsP76P9Uc9iTidGHi2KN34tL+ySvPAZ1DWLfR4lrjloe3PhHUMrYOg9pvv9lCfbL/23sAWyBsIII+YXohuXp/PR5hbYxRFyVQM4lizgXNICHc++RldqjlsLbd3uSzSaAmTftclcoL7hB2X7SkLKOlYaQl6lz+B9elo4Y92Zi8tv7t31SlgbjpDX9FUX0GOS/XIjvZX1xqe0lLuJgLTt6bo8X5rDCoXkNVNhvtzw=
#  file: "./src/distrib/MeshLab201804.dmg"
#  skip_cleanup: true
#  name: "MeshLab-$(date +'%Y%m%d')-beta"
#  prerelease: true
#  on:
#    repo: cnr-isti-vclab/meshlab
#    condition: $TRAVIS_OS_NAME = osx
